<?php
/**
 * 商品的SKU与第三的SKU绑定关系处理
 * 主要是将各平台的SKU属性 与 自己的SKU关联到一起。
 * 
 * User: afanti
 * Date: 2017/9/4
 * Time: 10:29
 */

class GudsSkuBindAction extends BaseAction{
    
    
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    
    
    public function getBindList()
    {
    
    }
    
    /**
     * 获取指定ID的SKU数据。
     */
    public function getSkuData()
    {
        $skuId = I('skuId');
        if (empty($skuId) && !preg_match ("/^([0-9]+)$/", $skuId)){
            $result = ['code' => 40012, 'msg' => L('INVALID_PARAMS'), 'data' => null];
            $this->jsonOut($result);
        }
        
        $optionModel = new GudsOptionModel();
        $skuData = $optionModel->getGudsOptionById($skuId);
        
        if (empty($skuData)){
            $result = ['code' => 50013, 'msg' => L('NOT_EXIST'), 'data' => null];
            $this->jsonOut($result);
        }
        
        $result = ['code' => 200, 'msg' => 'success', 'data' => $skuData];
        $this->jsonOut($result);
    }
    
    /**
     * 创建绑定关系
     */
    public function create()
    {
        $skuId = I('skuId');
        $thirdSkuId = I('thirdSkuId');
        $platformCode = I('platformCode');
        $storeCode = I('storeCode');
    
        if (empty($skuId) && !preg_match ("/^([0-9]+)$/", $skuId)){
            $result = ['code' => 40014, 'msg' => L('INVALID_PARAMS'), 'data' => null];
            $this->jsonOut($result);
        }
    
        if (empty($thirdSkuId) && !preg_match ("/^([0-9]+)$/", $thirdSkuId)){
            $result = ['code' => 40015, 'msg' => L('INVALID_PARAMS'), 'data' => null];
            $this->jsonOut($result);
        }
        
        if (empty($platformCode) || empty($storeCode)){
            $result = ['code' => 40016, 'msg' => L('INVALID_PARAMS'), 'data' => null];
            $this->jsonOut($result);
        }
        
        
        //检查是否已经存在绑定关系了
        
        
        
    }
    
    
    public function import()
    {
    
    }
    
    
    public function export()
    {
    
    }
    
    
    public function downloadTemplate()
    {
    
    }
    
    
    
}